### PR TITLE
[CALCITE-2266] Implement SQL:2016 JSON functions: JSON_EXISTS, JSON_V…

### PR DESCRIPTION
**Pull request by zhztheplayer**
This is the PR for [CALCITE-2266](https://issues.apache.org/jira/browse/CALCITE-2266).

### CODE REVIEW

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 1]
```diff
@@ -810,6 +824,642 @@ private void thereAndBack(byte[] bytes) {
...
+    assertThat(SqlFunctions.jsonStructuredValueExpression(100),
+        is(100));
+  }
+
+  @Test public void testJsonApiCommonSyntax() {
+    assertThat(
+        SqlFunctions.
+            jsonApiCommonSyntax(ImmutableMap.of("foo", "bar"),
+                "lax $.foo").pathReturned,
+        is("bar"));
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Please factor that to `assertJsonApiCommonSyntax_pathReturned` method so the exception message contains input, expected and actual values.

File: core/pom.xml [hunk 2]
```diff
@@ -96,6 +96,14 @@ limitations under the License.
       <groupId>com.yahoo.datasketches</groupId>
       <artifactId>sketches-core</artifactId>
     </dependency>
+    <dependency>
+      <groupId>org.ow2.asm</groupId>
+      <artifactId>asm</artifactId>
```
Comment (vlsi) [inline core/pom.xml]: Is `asm` dependency really required?

File: example/csv/sqlline [hunk 3]
```diff
@@ -41,6 +41,8 @@ if [ "$cygwin" ]; then
   VM_OPTS=-Djline.terminal=jline.UnixTerminal
 fi
 
+export TERM=xterm-color
```
Comment (vlsi) [inline example/csv/sqlline]: Is it intentional?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java (hunk 1 above)
Comment (zhztheplayer) [reply core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: +1 thanks.

File: example/csv/sqlline (hunk 3 above)
Comment (zhztheplayer) [reply example/csv/sqlline]: Not intentional, I will remove this.

File: core/pom.xml (hunk 2 above)
Comment (zhztheplayer) [reply core/pom.xml]: Jayway jsonpath is dependent on asm 5.0.x where elasticsearch-lang-painless uses 5.1, these two version has conflict producing NoSuchMethodError when running unit tests of calcite-elasticsearch.

What I have found is that jsonpath-2.4.0 is also working well with 5.1 version of asm, so I define this asm dependency explicitly to avoid the unit test failure.

A problem is that elasticsearch-lang-painless's asm is called `asm-debug-all` 5.1, and the jsonpath's asm is `asm` 5.1.

I am not sure the negative effect to have both of them included in dependency sets, but unit tests work well with that.

Comment (vlsi) [reply core/pom.xml]: That looks very odd.

1) `asm` is not used in Calcite code, so it should not be in `<dependency>`
2) Here's dependency tree:
```
[INFO] +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
[INFO] |  \- net.minidev:json-smart:jar:2.3:compile
[INFO] |     \- net.minidev:accessors-smart:jar:1.2:compile
[INFO] |        \- org.ow2.asm:asm:jar:5.0.4:compile
```

Looking into https://github.com/netplex/json-smart-v2/blob/master/accessors-smart/src/main/java/net/minidev/asm/BeansAccess.java#L54 , I am sure it could result in memory leaks, since it keeps strong references to the Class objects.

Is `accessors-smart` truly important? Are there other alternatives?

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 4]
```diff
@@ -419,6 +440,59 @@ public Expression implement(RexToLixTranslator translator,
...
+        BuiltInMethod.JSON_VALUE_EXPRESSION.method, NullPolicy.STRICT);
+    defineMethod(JSON_STRUCTURED_VALUE_EXPRESSION,
+        BuiltInMethod.JSON_STRUCTURED_VALUE_EXPRESSION.method, NullPolicy.STRICT);
+    defineMethod(JSON_API_COMMON_SYNTAX, BuiltInMethod.JSON_API_COMMON_SYNTAX.method,
+        NullPolicy.NONE);
+    defineMethod(JSON_EXISTS, BuiltInMethod.JSON_EXISTS.method, NullPolicy.NONE);
+    defineMethod(JSON_VALUE_ANY, BuiltInMethod.JSON_VALUE_ANY.method, NullPolicy.NONE);
+    defineMethod(JSON_QUERY, BuiltInMethod.JSON_QUERY.method, NullPolicy.NONE);
+    defineMethod(JSON_OBJECT, BuiltInMethod.JSON_OBJECT.method, NullPolicy.NONE);
+    aggMap.put(JSON_OBJECTAGG_NULL_ON_NULL, new Supplier<AggImplementor>() {
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Could you please use `() -> ` syntax here?
Or something like `aggMap.put(JSON_OBJECTAGG_NULL_ON_NULL, JsonObjectAggImplementor.for(BuiltInMethod.JSON_OBJECTAGG_ADD_ABSENT_ON_NULL))`

Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: +1 thanks.

File: core/pom.xml (hunk 2 above)
Comment (zhztheplayer) [reply core/pom.xml]: Thanks for your post, and you are right, the `asm-debug-all` is just a test dependency in current version of calcite, so `asm` is newly introduced compile dependency in my code. Does the `asm` itself have any problems to use?

And thanks for the notice about memory leak possibility of `accessors-smart`, I will try to deal with this problem.

Comment (zhztheplayer) [reply core/pom.xml]: I have take a look at the code of json-smart.

The ConcurrentHashMap java type cache seems to be safe in most senarios, unless:

1. the referenced type passed to json-smart is auto generated;
2. the referenced type passed to json-smart is varing dramatically.

As we don't need to pass any type reference to json-smart, and json-path does not generate class in runtime, I think the memory leak will not be triggered in general cases. What do you think?

After this I found that Json-Path has JSON provider configurations, as Jackson is already included by calcite, I have excluded json-smart from dependency set and use Jackson JSON provider instead.

Then there will be only 1 new jar `json-path:2.4.0` added to calcite, I think this is anyway better than introducing 4 new jars.

Comment (vlsi) [reply core/pom.xml]: >Does the asm itself have any problems to use?

ASM 5 does not support Java 9/10/11.
Adding ASM 5 now is a nonsense.

> The ConcurrentHashMap java type cache seems to be safe in most senarios

`Class` instance holds a string reference to its `ClassLoader`, so just a single strong reference to `java.lang.Class` is enough to keep the whole `ClassLoader` alive.

That is why `Cache<Class>` and/or `Cache<ClassLoader>` (which is the same thing) is almost always results in a memory leak unless the code is very robust.

If you can refrain from adding `asm` as a transitive dependency, that would be way easier to reason about (== no need to invent counter-cases, etc).

**Comment by zhztheplayer** [comment]
@vlsi Thank you very much for the code review, I have patched my changes.

File: core/src/main/java/org/apache/calcite/sql/fun/SqlJsonValueFunction.java [hunk 5]
```diff
@@ -0,0 +1,196 @@
...
+  }
+
+  private boolean isDefaultLiteral(SqlLiteral literal) {
+    return literal.getValueAs(SqlJsonValueEmptyOrErrorBehavior.class)
+        == SqlJsonValueEmptyOrErrorBehavior.DEFAULT;
+  }
+
+  private boolean canCastFrom(SqlCallBinding callBinding, boolean throwOnFailure,
+                              RelDataType inType, RelDataType outType) {
+    if (!SqlTypeUtil.canCastFrom(outType, inType, true)) {
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/sql/fun/SqlJsonValueFunction.java]: Please invert `if` condition and put shorter branches to the top in the cases like that.

The following is better than heavily nested code:
```
if (canCastFrom){
  return true;
}
if (!throwOnFailure) {
  return false;
}
throw ...
```

Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/sql/fun/SqlJsonValueFunction.java]: +1 thanks, and found a bug in line 120 and line 123 in the same file: the condition in if clause should be negative: ` if(canCastFrom) -> if (!canCastFrom)`

I will fix and add unit test for that.

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 6]
```diff
@@ -1723,6 +1789,97 @@ public Expression implementResult(AggContext info,
...
+    JsonObjectAggImplementor(Method m) {
+      this.m = m;
+    }
+
+    static Supplier<JsonObjectAggImplementor> supplierFor(Method m) {
+      return () -> new JsonObjectAggImplementor(m);
+    }
+
+    @Override public List<Type> getStateType(AggContext info) {
+      return Collections.singletonList(HashMap.class);
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Should it be `Map`?

Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Yes.

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 7]
```diff
@@ -1726,6 +1792,97 @@ public Expression implementResult(AggContext info,
...
+      return () -> new JsonObjectAggImplementor(m);
+    }
+
+    @Override public List<Type> getStateType(AggContext info) {
+      return Collections.singletonList(Map.class);
+    }
+
+    @Override public void implementReset(AggContext info,
+                                                   AggResetContext reset) {
+      // acc[0] = new HashMap();
```
Comment (michaelmior) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Looks like this can be removed

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 8]
```diff
@@ -1726,6 +1792,97 @@ public Expression implementResult(AggContext info,
...
+      reset.currentBlock().add(
+          Expressions.statement(
+              Expressions.assign(reset.accumulator().get(0),
+                  Expressions.new_(HashMap.class))));
+    }
+
+    @Override public void implementAdd(AggContext info,
+                                              AggAddContext add) {
+      // acc[0].put(arg0, arg1);
```
Comment (michaelmior) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Looks like this can be removed

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 9]
```diff
@@ -1726,6 +1792,97 @@ public Expression implementResult(AggContext info,
...
+    static Supplier<JsonArrayAggImplementor> supplierFor(Method m) {
+      return () -> new JsonArrayAggImplementor(m);
+    }
+    @Override public List<Type> getStateType(AggContext info) {
+      return Collections.singletonList(List.class);
+    }
+
+    @Override public void implementReset(AggContext info,
+                                         AggResetContext reset) {
+      // acc[0] = new HashMap();
```
Comment (michaelmior) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Looks like this can be removed

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 10]
```diff
@@ -1726,6 +1792,97 @@ public Expression implementResult(AggContext info,
...
+      reset.currentBlock().add(
+          Expressions.statement(
+              Expressions.assign(reset.accumulator().get(0),
+                  Expressions.new_(ArrayList.class))));
+    }
+
+    @Override public void implementAdd(AggContext info,
+                                       AggAddContext add) {
+      // acc[0].put(arg0, arg1);
```
Comment (michaelmior) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Looks like this can be removed

File: core/src/main/java/org/apache/calcite/sql/SqlKind.java [hunk 11]
```diff
@@ -721,6 +721,26 @@
...
+   */
+  JSON_VALUE_EXPRESSION,
+
+  /**
+   * The JSON API common syntax.
+   */
+  JSON_API_COMMON_SYNTAX,
+
+  /**
+   *
```
Comment (michaelmior) [inline core/src/main/java/org/apache/calcite/sql/SqlKind.java]: Seems like a comment is missing here (and below)

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java (hunk 7 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Done.

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java (hunk 8 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Done.

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java (hunk 9 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Done.

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java (hunk 10 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Done.

File: core/src/main/java/org/apache/calcite/sql/SqlKind.java (hunk 11 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/sql/SqlKind.java]: Done, thanks!

File: core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java [hunk 12]
```diff
@@ -1726,6 +1792,93 @@ public Expression implementResult(AggContext info,
...
+    }
+
+    @Override public Expression implementResult(AggContext info,
+                                                       AggResultContext result) {
+      return Expressions.call(BuiltInMethod.JSONIZE.method,
+          result.accumulator().get(0));
+    }
+  }
+
+  /** Implementor for the {@code JSON_ARRAYAGG} windowed aggregate function. */
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Do you really mean `windowed` here?

Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/adapter/enumerable/RexImpTable.java]: Mistaken here，it‘s corrected now.

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 13]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+    assertJsonApiCommonSyntax(ImmutableMap.of("foo", "bar"), "lax $.foo1",
+        SqlFunctions.PathContext.withReturned(SqlFunctions.PathMode.LAX, null));
+    assertJsonApiCommonSyntax(ImmutableMap.of("foo", "bar"), "strict $.foo1",
+        SqlFunctions.PathContext.withStrictException(
+            new PathNotFoundException("No results for path: $['foo1']")));
+    assertJsonApiCommonSyntax(ImmutableMap.of("foo", 100), "lax $.foo",
+        SqlFunctions.PathContext.withReturned(SqlFunctions.PathMode.LAX, 100));
+  }
+
+  @Test public void testJsonExists() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?
Note: you might find `@Parameterized` tests convenient to enumerate test cases.

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 14]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+          jsonExists(SqlFunctions.PathContext
+                  .withStrictException(new Exception("test message")),
+              SqlJsonExistsErrorBehavior.ERROR);
+      fail("expect exception, but not");
+    } catch (RuntimeException e) {
+      assertThat(e.getMessage(), is("java.lang.Exception: test message"));
+    }
+  }
+
+  @Test public void testJsonValueAny() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 15]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+              null,
+              SqlJsonValueEmptyOrErrorBehavior.ERROR,
+              null);
+      fail("expect exception, but not");
+    } catch (Exception e) {
+      assertThat(e.getMessage(), is("java.lang.RuntimeException: not a json value: []"));
+    }
+  }
+
+  @Test public void testJsonQuery() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 16]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+                SqlFunctions.PathContext
+                    .withReturned(SqlFunctions.PathMode.STRICT, Collections.singletonList("bar")),
+                SqlJsonQueryWrapperBehavior.WITH_CONDITIONAL_ARRAY,
+                SqlJsonQueryEmptyOrErrorBehavior.NULL,
+                SqlJsonQueryEmptyOrErrorBehavior.NULL),
+        is("[\"bar\"]")
+    );
+  }
+
+  @Test public void testJsonize() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Please either correct test method name or add a human-readable message to the testcase

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 17]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+    );
+    assertThat(
+        SqlFunctions.dejsonize("[]"),
+        is(Collections.emptyList())
+    );
+
+    // expect exception thrown
+    try {
+      SqlFunctions.dejsonize("[}");
+      fail("expect exception, but not");
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Please use `SqlFunctions.dejsonize("[}") should throw exception` message

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 18]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+    } catch (Exception ignored) {
+      // ignored
+    }
+  }
+
+  @Test public void testJsonObject() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 19]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+    );
+    assertThat(
+        SqlFunctions.jsonObject(SqlJsonConstructorNullClause.ABSENT_ON_NULL,
+            "foo",
+            null),
+        is("{}")
+    );
+  }
+
+  @Test public void testJsonObjectAggAdd() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 20]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+        is(expected)
+    );
+    SqlFunctions.jsonObjectAggAdd(map,
+        "foo2", null, SqlJsonConstructorNullClause.ABSENT_ON_NULL);
+    assertThat(map,
+        is(expected)
+    );
+  }
+
+  @Test public void testJsonArray() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 21]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+    );
+    assertThat(
+        SqlFunctions.jsonArray(SqlJsonConstructorNullClause.ABSENT_ON_NULL,
+            "foo",
+            null),
+        is("[\"foo\"]")
+    );
+  }
+
+  @Test public void testJsonArrayAggAdd() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java [hunk 22]
```diff
@@ -810,6 +826,674 @@ private void thereAndBack(byte[] bytes) {
...
+        is(expected)
+    );
+    SqlFunctions.jsonObjectAggAdd(map,
+        "foo2", null, SqlJsonConstructorNullClause.ABSENT_ON_NULL);
+    assertThat(map,
+        is(expected)
+    );
+  }
+
+  @Test public void testJsonPredicate() {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: Would you please ensure the tests print human-understandable messages in case of failures?

File: pom.xml [hunk 23]
```diff
@@ -941,6 +953,9 @@ limitations under the License.
             <additionalOptions>
               <additionalOption>${maven-javadoc-html5}</additionalOption>
             </additionalOptions>
+            <additionalJOptions>
+              <additionalJOption>-J-Xss4m</additionalJOption>
```
Comment (vlsi) [inline pom.xml]: Is this an intentional change? Why is it required?

Comment (zhztheplayer) [reply pom.xml]: Increasing amount of keywords could lead to StackOverflowError during Travis CI, both at compile time and javadoc generation time, This is a workaround for javadoc, however I am not sure if the issue still exists after commit https://github.com/apache/calcite/commit/561c6427e3602510d619b45cd7da840773fa0d2c, I will make a test.

File: core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java (hunk 1 above)
Comment (zhztheplayer) [reply core/src/test/java/org/apache/calcite/test/SqlFunctionsTest.java]: @vlsi Thanks, I see your comments both in PR and JIRA, I will try do an optimization.

File: core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java [hunk 24]
```diff
@@ -0,0 +1,752 @@
...
+import static org.hamcrest.CoreMatchers.is;
+import static org.hamcrest.CoreMatchers.nullValue;
+import static org.junit.Assert.assertThat;
+import static org.junit.Assert.fail;
+
+/**
+ * `
+ * Unit test for the methods in {@link SqlFunctions} that implement JSON processing functions.
+ */
+public class SqlJsonFunctionsTest {
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java]: Please add the file to `CalciteSuite`

Comment (zhztheplayer) [reply core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java]: Fixed. Thanks for pointing out this!

File: core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java [hunk 25]
```diff
@@ -0,0 +1,752 @@
...
+    try {
+      SqlFunctions
+          .jsonValueAny(
+              SqlFunctions.PathContext
+                  .withReturned(SqlFunctions.PathMode.LAX, Collections.emptyList()),
+              SqlJsonValueEmptyOrErrorBehavior.ERROR,
+              null,
+              SqlJsonValueEmptyOrErrorBehavior.NULL,
+              null);
+      fail("expect exception, but not");
```
Comment (vlsi) [inline core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java]: It is sad that exception message does not clarify the reason.
There are "obvious" `fail(...)`, however this one is not clear from the first sight.

Comment (zhztheplayer) [reply core/src/test/java/org/apache/calcite/test/SqlJsonFunctionsTest.java]: @vlsi I have made individual failure check methods in latest commit, please check it.

File: core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java [hunk 26]
```diff
@@ -2425,6 +2449,381 @@ public static Object structAccess(Object structObject, int index, String fieldNa
...
+
+  public static Object jsonStructuredValueExpression(Object input) {
+    return input;
+  }
+
+  public static PathContext jsonApiCommonSyntax(Object input, String pathSpec) {
+    try {
+      Matcher matcher = JSON_PATH_BASE.matcher(pathSpec);
+      if (!matcher.matches()) {
+        throw new RuntimeException("illegal patch spec, missing mode declaration");
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java]: Should error message start with a capital and include `pathSpec` in question?

File: core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java [hunk 27]
```diff
@@ -2425,6 +2449,381 @@ public static Object structAccess(Object structObject, int index, String fieldNa
...
+          throw new RuntimeException("empty json value");
+        case NULL:
+          return null;
+        case DEFAULT:
+          return defaultValueOnEmpty;
+        default:
+          throw new RuntimeException("illegal empty behavior: " + emptyBehavior);
+        }
+      } else if (context.mode == PathMode.STRICT && !isScalarObject(value)) {
+        exc = new RuntimeException("not a json value: " + value);
```
Comment (vlsi) [inline core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java]: I wonder if we should use `RuntimeExceptions` for errors like this.
Should `CalciteResource` be used?
Should the message help user more to understand and resolve the failure?

E.g. "strict jsonpath mode requires scalar value, and the actual value is: ..."

**Comment by vlsi** [comment]
The PR looks good to me modulo `RuntimeException` use for error signaling and error messages.
Certain messages start with lowercase, and it probably makes sense to elaborate messages so they help user to understand and resolve the issue.

CalciteResources would enable use of translated messages.

I don't think it blocks the PR, however I think proper exception messages are more important than, for instance, commit messages

File: core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java (hunk 26 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java]: Agree.

File: core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java (hunk 27 above)
Comment (zhztheplayer) [reply core/src/main/java/org/apache/calcite/runtime/SqlFunctions.java]: If we use CalciteResource we should factor the previous usages of RuntimeException in other function code too, to keep consistency. If it is OK I can do the work in this PR.

**Comment by vlsi** [comment]
Looks good to me, many thanks

**Comment by michaelmior** [comment]
Thanks for the continued review @vlsi. Do you plan to merge? Otherwise I can.

**Comment by vlsi** [comment]
@michaelmior , would you please merge?
